apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      {{- include "pipeline.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pipeline.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: false # TODO enable this again or at least make it configurable
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --leader-elect
          env:
            - name: NODE_SELECTOR_MAP
              value: "{{ .Values.env.nodeSelectorMap }}"
            - name: STORAGE_CLASS
              value: "{{ .Values.env.storageClass }}"
            - name: IMAGE_REPO_CLASS_LABEL
              value: "{{ .Values.env.imageRepoClassLabel }}"
            - name: IMAGE_REPO_CLASSES_MAP
              value: "{{ .Values.env.imageRepoClassesMap }}"
            - name: JOB_IMAGE_PREFIX
              value: "{{ .Values.env.jobImagePrefix }}"
            - name: RESOURCE_ESTIMATION_SERVICE
              value: "{{ .Values.env.resourceEstimationService }}"
            - name: CREATE_PIPELINE_SERVICE_ACCOUNTS
              value: "{{ .Values.env.createPipelineServiceAccounts }}"
            - name: SERVICE_ACCOUNT_LABEL_KEY
              value: "{{ .Values.env.serviceAccountLabelKey }}"
            - name: SERVICE_ACCOUNT_LABEL_VALUE_PATTERN
              value: "{{ .Values.env.serviceAccountLabelValuePattern }}"
            - name: CREATE_SCHEDULER_SERVICE_ACCOUNT
              value: "{{ .Values.env.createSchedulerServiceAccount }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "pipeline.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
