{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-scheduler
rules:
  - apiGroups:
      - pipeline.k-pipe.cloud
    resources:
      - pipelineschedules
    verbs:
      - create
      - get
      - list
      - watch
      - patch
{{- end }}