{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-developer
rules:
  - apiGroups:
      - pipeline.k-pipe.cloud
    resources:
      - pipelinedefinitions
      - pipelineruns
      - pipelineschedules
      - pipelinejobs
      - pipelineproblems
      - pipelinemanagedimages
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
      - serviceaccounts
      - configmaps
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
{{- end }}